### Input Layer

The **input layer** is the first part of a CNN. It receives the image and passes it to the next layer.

For an image, the input shape depends on:

- **Height** – number of rows of pixels
- **Width** – number of columns of pixels
- **Channels** – number of color channels

For example, an RGB image of size `32 × 32` has:

`32 × 32 × 3`

Here:
- `32` = height
- `32` = width
- `3` = RGB channels

In PyTorch, CNN images are usually represented as:

`[Batch Size, Channels, Height, Width]`

Example:

`[32, 3, 32, 32]`

This means:
- `32` images in one batch
- `3` color channels
- `32` pixels high
- `32` pixels wide

The input layer does not learn features. It simply provides the image data to the CNN.

In [1]:

import torch

# 32 RGB images of size 32x32
images = torch.randn(32, 3, 32, 32)

print(images.shape)


torch.Size([32, 3, 32, 32])


This confirms that the CNN receives the images in the format:

`Batch × Channels × Height × Width`

# Real-world example:

A CNN detecting whether an image contains a cat or dog first receives the image through the input layer. The image is then passed to convolution layers for feature extraction.

### Convolution Layers

A **convolution layer** is the main feature-extraction layer in a CNN.

It uses small learnable **filters (kernels)** to scan across the input image and detect useful patterns.

A convolution layer can learn to detect features such as:

- Edges
- Corners
- Lines
- Textures
- Shapes

The first convolution layers usually learn **simple features**. Deeper convolution layers can learn **more complex features**.

For example:

`Image → Convolution → Feature Map`

A convolution layer has learnable **weights**, so during training the CNN learns which patterns are important.

In a CNN architecture, multiple convolution layers can be stacked:

`Input → Conv → Conv → Conv`

Adding more convolution layers allows the network to learn increasingly complex features.

In [2]:

import torch
import torch.nn as nn

# Input: 1 image, 3 channels, 32x32
image = torch.randn(1, 3, 32, 32)

# Convolution layer
conv = nn.Conv2d(
    in_channels=3,
    out_channels=16,
    kernel_size=3
)

output = conv(image)

print(output.shape)


torch.Size([1, 16, 30, 30])


```

**Output:**
```text
torch.Size([1, 16, 30, 30])
```

Here:

- `3` input channels = RGB
- `16` output channels = 16 learned filters
- `3 × 3` = filter size
- `16` feature maps are produced

The spatial size changes from `32 × 32` to `30 × 30` because padding was not used.

## Real-world example:
In a face-recognition CNN, early convolution layers may learn edges and simple shapes, while later convolution layers can combine those features to recognize eyes, nose, and other facial patterns.

### Activation Layers

An **activation layer** applies an activation function to the output of a convolution layer.

The activation function introduces **non-linearity** into the CNN. This allows the network to learn complex patterns instead of only simple linear relationships.

A commonly used activation function in CNNs is **ReLU (Rectified Linear Unit)**.

ReLU works like this:

- Positive value → remains unchanged
- Negative value → becomes `0`

Example:

`[-2, 0, 3, 5] → [0, 0, 3, 5]`

A typical CNN architecture uses activation after convolution:

`Input → Convolution → ReLU`

Multiple convolution and activation layers can be used:

`Input → Conv → ReLU → Conv → ReLU`

ReLU is widely used because it is simple and helps CNNs learn efficiently.

In [3]:

import torch
import torch.nn as nn

x = torch.tensor([-2.0, 0.0, 3.0, 5.0])

relu = nn.ReLU()

output = relu(x)

print(output)


tensor([0., 0., 3., 5.])


```

**Output:**
```text
tensor([0., 0., 3., 5.])
```

The negative value `-2` becomes `0`, while positive values remain unchanged.

# Real-world example:
In an image-classification CNN, the convolution layer may detect an edge. ReLU helps the network keep useful positive signals while removing negative activations.

### Pooling Layers

A **pooling layer** reduces the spatial size of feature maps.

It helps to:

- Reduce the amount of computation
- Reduce the number of values the network needs to process
- Keep important features

The most commonly used type is **Max Pooling**.

**Max Pooling** selects the largest value from a small region.

For example:

`[1  5]`
`[2  3]`

Max Pooling returns:

`5`

A common CNN structure is:

`Convolution → ReLU → Pooling`

For example:

`32 × 32 → Convolution → 32 × 32 → Max Pooling → 16 × 16`

Pooling therefore makes the feature map smaller while retaining important information.

In [4]:

import torch
import torch.nn as nn

x = torch.tensor([
    [[
        [1.0, 5.0, 2.0, 4.0],
        [3.0, 7.0, 1.0, 2.0],
        [6.0, 2.0, 8.0, 3.0],
        [1.0, 4.0, 5.0, 9.0]
    ]]
])

pool = nn.MaxPool2d(kernel_size=2)

output = pool(x)

print(output)


tensor([[[[7., 4.],
          [6., 9.]]]])


```

**Output:**
```text
tensor([[[[7., 4.],
          [6., 9.]]]])
```

The `2 × 2` pooling operation selects the **largest value** from each `2 × 2` region

### Batch Normalization

**Batch Normalization (BatchNorm)** normalizes the values produced by a layer during training.

In a CNN, the values passed between layers can vary. Batch normalization helps keep these values in a more stable range.

It can help the network:

- Train more smoothly
- Train faster
- Improve training stability

A common CNN structure is:

`Convolution → Batch Normalization → ReLU`

For example:

`Input → Conv → BatchNorm → ReLU → Pooling`

Batch normalization is especially useful when building deeper CNN architectures because it can make training more stable.

In [5]:

import torch
import torch.nn as nn

x = torch.randn(8, 16, 32, 32)

batch_norm = nn.BatchNorm2d(16)

output = batch_norm(x)

print(output.shape)


torch.Size([8, 16, 32, 32])


```

**Output:**
```text
torch.Size([8, 16, 32, 32])
```

The shape does not change.

Batch normalization changes the values, but it keeps the same:

`Batch × Channels × Height × Width`

# Real-world example:
When training an image-classification CNN, BatchNorm helps keep the values flowing through the network stable, making training easier, especially as the CNN becomes deeper.

### Dropout

**Dropout** is a regularization technique used to reduce **overfitting** in a neural network.

During training, dropout randomly sets some neuron outputs to `0`.

For example, if a layer has:

`[2, 4, 6, 8]`

Dropout might temporarily remove some values:

`[2, 0, 6, 0]`

This forces the network to learn using different combinations of neurons instead of depending too much on specific neurons.

A CNN architecture may use dropout before the fully connected layers:

`Convolution → ReLU → Pooling → Dropout → Fully Connected`

Dropout is active during **training**, but it is automatically disabled during **evaluation/testing**.

In [6]:

import torch
import torch.nn as nn

x = torch.ones(10)

dropout = nn.Dropout(p=0.5)

dropout.train()
output = dropout(x)

print(output)


tensor([0., 0., 2., 0., 2., 2., 2., 0., 0., 0.])


```

**Example output:**
```text
tensor([2., 0., 2., 2., 0., 0., 2., 2., 0., 2.])
```

Here:

- `p=0.5` means approximately 50% of the values may be dropped during training.
- Dropped values become `0`.
- The remaining values are scaled so the expected output remains consistent.

# Real-world example:
If a CNN is trained to recognize objects and becomes too dependent on a few specific features, dropout helps prevent this dependency and improves generalization to new images.

### Fully Connected Layers

A **Fully Connected (FC) layer**, also called a **Linear layer**, is usually placed near the end of a CNN.

The convolution and pooling layers extract useful features from the image. The fully connected layers use these extracted features to make the final prediction.

Before passing the feature maps to a fully connected layer, they are **flattened** into a one-dimensional vector.

Example:

`Feature Maps → Flatten → Fully Connected Layer`

Suppose the feature maps have the shape:

`16 × 4 × 4`

After flattening:

`16 × 4 × 4 = 256 values`

These 256 values can then be passed to a fully connected layer.

A simple CNN flow is:

`Input → Convolution → ReLU → Pooling → Flatten → Fully Connected`

The fully connected layer combines the learned features to help determine the class of the image.

In [7]:

import torch
import torch.nn as nn

# 1 image, 16 feature maps, 4x4
x = torch.randn(1, 16, 4, 4)

# Flatten
x = torch.flatten(x, start_dim=1)

print(x.shape)

# Fully connected layer
fc = nn.Linear(16 * 4 * 4, 10)

output = fc(x)

print(output.shape)


torch.Size([1, 256])
torch.Size([1, 10])


```

**Output:**
```text
torch.Size([1, 256])
torch.Size([1, 10])
```

Here:

- `16 × 4 × 4` = 256 input values
- `256` = input features to the FC layer
- `10` = 10 output values/classes

### Experiment with Different CNN Architectures

A CNN can be designed with different numbers of layers and different numbers of filters.

We can experiment with three architectures:

**1. Shallow CNN**

A small network with fewer convolution layers.

`Input → Conv → ReLU → Pooling → FC → Output`

It is:
- Simple
- Faster to train
- Requires fewer computational resources
- May not learn complex features well

**2. Medium CNN**

A larger network with more convolution layers.

`Input → Conv → ReLU → Pooling → Conv → ReLU → Pooling → FC → Output`

It can learn more complex features than a shallow CNN but requires more computation.

**3. Deeper CNN**

A network with several convolution blocks.

`Input → Conv → ReLU → Pooling → Conv → ReLU → Pooling → Conv → ReLU → Pooling → FC → Output`

It can learn more complex features but requires:
- More computation
- More memory
- More training time

We can compare these architectures using the same dataset, training process, and evaluation method. This helps us understand whether adding more layers actually improves the model.

In [8]:

import torch.nn as nn

# Shallow CNN
shallow_cnn = nn.Sequential(
    nn.Conv2d(3, 16, 3),
    nn.ReLU(),
    nn.MaxPool2d(2),
    nn.Flatten(),
    nn.Linear(16 * 15 * 15, 10)
)

# Medium CNN
medium_cnn = nn.Sequential(
    nn.Conv2d(3, 16, 3),
    nn.ReLU(),
    nn.MaxPool2d(2),

    nn.Conv2d(16, 32, 3),
    nn.ReLU(),
    nn.MaxPool2d(2),

    nn.Flatten(),
    nn.Linear(32 * 6 * 6, 10)
)

# Deeper CNN
deeper_cnn = nn.Sequential(
    nn.Conv2d(3, 16, 3),
    nn.ReLU(),
    nn.MaxPool2d(2),

    nn.Conv2d(16, 32, 3),
    nn.ReLU(),
    nn.MaxPool2d(2),

    nn.Conv2d(32, 64, 3),
    nn.ReLU(),
    nn.MaxPool2d(2),

    nn.Flatten(),
    nn.Linear(64 * 2 * 2, 10)
)
